package com.hcsc.generic.ingest.confgen.render

import com.typesafe.config.{Config, ConfigRenderOptions, ConfigValue, ConfigValueType}

import scala.collection.JavaConverters._

/**
  * Readable HOCON emitter for generated feed files.
  *
  * The framework consumes ONE logical configuration; on disk it is split for
  * maintainability: the potentially very large schema contract (the
  * source-to-target mapping document) goes to `<entity>-schema.conf` and is
  * pulled into the feed block with `include required(...)`. HOCON includes
  * are resolved natively by ConfigFactory.parseFile relative to the
  * including file, so the runtime pipeline needs no changes.
  *
  * Sections are emitted in a fixed logical reading order (identity, source,
  * schema, governance, destinations) instead of the renderer's alphabetical
  * order.
  */
object HoconFeedWriter {

  /** Logical section order; keys not listed are appended alphabetically. */
  private val SectionOrder = Seq(
    "entity", "mode", "source", "schema", "rejects", "idempotency",
    "audit", "concurrency", "watermark", "raw", "curated")

  private val Render = ConfigRenderOptions.defaults()
    .setOriginComments(false).setComments(false).setJson(false).setFormatted(true)

  /** File name of the standalone schema contract for an entity. */
  def schemaFileName(entity: String): String = s"$entity-schema.conf"

  def renderMain(entity: String, feed: Config, schemaInclude: Option[String]): String = {
    val root = feed.root()
    val keys = root.keySet().asScala.toSet
    val ordered = SectionOrder.filter(keys.contains) ++
      (keys -- SectionOrder.toSet).toSeq.sorted
    val entries = ordered.flatMap { key =>
      if (key == "schema" && schemaInclude.isDefined) None
      else Some(entry(key, root.get(key), "  "))
    }

    val out = new StringBuilder
    out.append(s"# Feed configuration for '$entity' — generated by ConfigGeneratorMain.\n")
    schemaInclude.foreach { f =>
      out.append("# The schema contract (source-to-target mapping document) is maintained\n")
      out.append(s"# separately in $f and included below.\n")
    }
    out.append("\n")
    out.append(s"feeds.${quoteSegment(entity)} {\n")
    schemaInclude.foreach(f => out.append("  include required(\"" + f + "\")\n\n"))
    out.append(entries.mkString("\n\n"))
    out.append("\n}\n")
    out.toString
  }

  /** Contents of the standalone schema file; None when the feed has no contract. */
  def renderSchema(entity: String, feed: Config): Option[String] =
    if (!feed.hasPath("schema")) None
    else Some(
      s"# Schema contract (source-to-target mapping) for feed '$entity'.\n" +
        s"# Included by $entity.conf via `include required(...)` — maintain the column\n" +
        "# mappings here. Per column: name (canonical/target name), type, nullable,\n" +
        "# required, aliases (accepted source names), position, default, and\n" +
        "# validation { regex, min_length, max_length, allowed_values, ... }.\n" +
        "\n" +
        entry("schema", feed.root().get("schema"), "") +
        "\n")

  private def entry(key: String, value: ConfigValue, indent: String): String = {
    // Render through a single-entry holder config: a bare ConfigObject
    // renders as a braceless root in HOCON mode, so rendering the value
    // directly would splice its body into the parent scope.
    val holder = com.typesafe.config.ConfigFactory.empty().withValue(quoteSegment(key), value)
    holder.root().render(Render).trim
      .linesIterator
      .map(line => if (line.isEmpty) line else indent + line)
      .mkString("\n")
  }

  private def quoteSegment(segment: String): String =
    if (segment.matches("[a-zA-Z0-9_-]+")) segment else "\"" + segment + "\""
}
